[project]
name = "data-devcontainer"
version = "0.1.0"
description = "A Basic Template Dev Container for Data Analysis and Data Pipeline Project in Python with Duck DB"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.4.0",
]
